name: Deal Scraper

on:
  schedule:
    # Exécute le script toutes les 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Permet de le lancer manuellement aussi

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 supabase

      - name: Run scraper
        run: python bot.py
        env:
          # On injecte le secret dans le script
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
